# Generated by Django 4.0.4 on 2022-06-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0004_customuser_image_customuser_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='post_files/'),
        ),
    ]
